reserved_status_added
Philiuh/tesk_task_ruport pull request #3
Opened 2022-02-11 14:46 UTC by Philiuh

2022-02-18 10:20 UTC, BogdanovBogdan commented on dev/res/js-dev/components/fetch/renderCards.js
> +export default async () => {
Такс, с линтером мы поговорим вместе, а на счет статьи, к которой говорится об использовании async без await попрошу ссылку, интересно посмотреть что там пишется)

2022-02-18 10:28 UTC, BogdanovBogdan commented on dev/res/js-dev/components/fetch/renderCards.js
> +export default async () => {
Я тут покопался в интернетах этих наших, нашел и ЗА и ПРОТИВ:
ЗА: [ссылка](https://stackoverflow.com/questions/45594596/async-function-without-await-in-javascript#:~:text=One%20benefit%20to%20declaring%20%27async%27%20in%20a%20function%20that%20returns%20a%20promise%20but%20doesn%27t%20use%20await%20is%20that%20exceptions%20will%20be%20rejected%20instead%20of%20synchronously%20thrown.%20e.g.%20const%20result%20%3D%20someAsyncFunctionWithoutAwait().catch(handleRejection))
ПРОТИВ: [ссылка](https://stackoverflow.com/questions/45594596/async-function-without-await-in-javascript#:~:text=Everything%20is%20synchronous%20until%20a%20JavaScript%20asynchronous%20function%20is%20executed.%20In%20using%20async%2Dawait%2C%20await%20is%20asynchronous%20and%20everything%20after%20await%20is%20placed%20in%20the%20event%20queue.%20It%20is%20similar%20to%20.then().)

Но в случае, где ЗА async без await говорится что это может быть полезным для обработки ошибок, но в твоем случае это вроде бы не нужно

2022-02-18 10:53 UTC, Philiuh commented on dev/res/js-dev/components/fetch/renderCards.js
> +export default async () => {
Да в любой статье где говорится об использовании async говорится что это просто функция, которая возвращает промис https://learn.javascript.ru/async-await 
![image](https://user-images.githubusercontent.com/37549039/154668867-b0a24958-d451-4054-881d-5ffda6e3a4bc.png)
Или вот тут https://www.w3schools.com/js/js_async.asp
Когда говорят про async await - то всегда говорят сперва про то что async функции возвращают промис, а потом говорят о возможности юзать await для ожидания выполнения промиса

2022-02-18 11:43 UTC, BogdanovBogdan requested changes

2022-02-18 11:43 UTC, BogdanovBogdan commented on dev/res/sass/components/footer/_footer.scss
> +  @include container-width($contentWidthDesktopMax);
а у тебя футер на всех разрешениях будет расчитываться от одной ширины?

2022-02-18 11:43 UTC, BogdanovBogdan commented on dev/res/sass/components/menu/_menu.scss
> +  @media (max-width: 720px) {
Если вынесешь ширину для медиа-запроса в переменную, то в дальнейшем будет проще работать с ней, например, если нужно будет изменить ее. 
И в целом старайся выносить значения, которые используются часто, в переменные

2022-02-18 11:43 UTC, BogdanovBogdan commented on dev/res/sass/components/menu/_menu.scss
> +  content: '';
для псевдоэлементов в этом шаблоне можно использовать миксин tx-pseudo, который уже содержит в себе некоторые css сво-ва, в т.ч. content

2022-02-18 11:43 UTC, BogdanovBogdan commented on dev/res/templates/components/header/_header.html
> +    <a class="header-icon" href="">
По нажатию на лого, обычно переходят на главную страницу, поэтому можно в href записать слеш / как указатель на главную страницу.
Но вообще, обычно, если ссылка никуда не должна вести, то в href добавляют #

Вот какую систему с href еще нашел и что будет происходить по клику на ссылку:
Если пусто: перезагрузится страница
Если /: перейдет на главную страницу
Если #: страница не перезагрузится, но произойдет сролл на верх страницы
Если javascript:void(0);: ничего не произойдет

Выбирай подходящее для лого)

2022-02-18 11:43 UTC, BogdanovBogdan commented on dev/res/templates/components/menu/_menu.html
> +    <div class="menu-inner">
можно без лишней обретки обойтись)

2022-02-18 12:50 UTC, Philiuh commented on dev/res/sass/components/footer/_footer.scss
> +  @include container-width($contentWidthDesktopMax);
Да. Тк там идет центрирование одного элемента - то неважно на каком разрешении это будет. И для оптимизации решил так сделать

2022-02-18 13:22 UTC, Philiuh commented on dev/res/templates/components/menu/_menu.html
> +    <div class="menu-inner">
Если ты menu-inner - то это задел под будущее. Потом по макету нужно будет селектор влепить, и тут уже он пригодится

2022-02-18 13:30 UTC, Philiuh commented on dev/res/sass/components/menu/_menu.scss
> +  @media (max-width: 720px) {
Разве можно в медиа-запросы вставлять переменные? Не нашел инфы в гугле

2022-02-18 15:08 UTC, BogdanovBogdan commented on dev/res/templates/components/menu/_menu.html
> +    <div class="menu-inner">
обговорили, что все таки можем обойтись без обертки

2022-02-22 09:35 UTC, BogdanovBogdan requested changes

2022-02-22 09:35 UTC, BogdanovBogdan commented on dev/res/sass/components/menu/_menu.scss
> +  @media (max-width: 720px) {
Предлагаю использовать в качестве конструкции для медиа запросов миксин tx-media, чтобы на всем проекте было одинаково)

2022-02-22 09:35 UTC, BogdanovBogdan commented on dev/res/templates/components/menu/_menu.html
> +    <div class="menu-inner">
Такс, еще не убрал, забыл или сложности какие-то?)

2022-02-22 13:05 UTC, merged

2022-02-25 08:47 UTC, BogdanovBogdan approved these changes