modal_added
Philiuh/tesk_task_ruport pull request #4
Opened 2022-03-09 01:01 UTC by Philiuh

2022-03-09 08:01 UTC, Philiuh commented on dev/res/js-dev/scripts.js
> +renderCards().then(filterCards).then(renderModal);
забыл зарефакторить эту длинную цепочку промисов

2022-03-09 08:02 UTC, Philiuh commented on dev/res/sass/components/card/_card-reserved.scss
> +
забыл заменить значения container-width на переменные.....

2022-03-09 08:03 UTC, Philiuh commented on dev/res/templates/components/modal/_modal.html
> +</div>
забыл удалить файл ы

2022-03-11 10:14 UTC, BogdanovBogdan requested changes

2022-03-11 10:31 UTC, BogdanovBogdan requested changes

2022-03-11 10:31 UTC, BogdanovBogdan commented on dev/res/js-dev/components/modal/renderModal.js
> +    <div class="card ${cardData.in_reserve ? 'reserved' : ''} card--modal">
используй деструктуризацию для параметров объекта `cardData` так будет более читабельно

2022-03-11 10:31 UTC, BogdanovBogdan commented on dev/res/js-dev/components/modal/renderModal.js
> +// норм ли засовывать document.body в переменную, или лучше обойтись без переменной?
нууу, этого никто не запрещает, но смысл в этой ситуации так делать... кода не много сократиться, читабельнее не станет

2022-03-16 09:31 UTC, BogdanovBogdan commented on dev/res/js-dev/components/fetch/renderCards.js
> +/* eslint-disable camelcase */
Лучше отключать правило еслинта для конкретной строки, чтобы это работало только там, где нужно

2022-03-16 09:57 UTC, BogdanovBogdan commented on dev/res/js-dev/components/modal/renderModal.js
> +// чтоб не выглядело ебано
хорошо) Только отключи еслинт для этой строки

`// eslint-disable-next-line no-alert`

2022-03-16 10:00 UTC, BogdanovBogdan commented on dev/res/js-dev/components/modal/renderModal.js
> +const renderModal = (cardData, error) => {
второй параметр не приходит сюда из фетча же

2022-03-16 13:16 UTC, BogdanovBogdan commented on dev/res/js-dev/components/modal/renderModal.js
> +          ? '<div class="reserved-img"><p class="reserved-announcement reserved-announcement--modal">В заповеднике</p></div>'
это можно сделать псевдоэлементами для ноды reserved

2022-03-16 13:23 UTC, BogdanovBogdan commented on dev/res/js-dev/components/modal/renderModal.js
> +      <img src="${image_url}" class="card-img--modal">
тут тоже самостоятельный элемент, не совсем корректно задавать ему модификатор.
У тебя уже есть класс `card-img`, если нужно изменить какие-то стили именно для модалки, то просто это делаешь через наследование `.modal .card-img`, но только по scss, вот как это будет выглядеть:
![image](https://user-images.githubusercontent.com/49097483/158599524-33e42146-e476-4bc2-afdd-b9ebf4e4f56e.png)

`%modal` - это экстенд который объявляется в классе `.modal`, вот так:
![image](https://user-images.githubusercontent.com/49097483/158599808-7fa9765f-924b-4335-86fb-969332f3356d.png)

2022-03-16 13:30 UTC, BogdanovBogdan commented on dev/res/js-dev/components/modal/renderModal.js
> +      } card-name--modal">${name}</h2>
тоже самое с остальной версткой в этом файле

2022-03-16 13:57 UTC, BogdanovBogdan commented on dev/res/js-dev/components/modal/renderModal.js
> +  modalCard = document.querySelector('.modal');
если мы статично оставим верску для обертки модалки (modal) и внутри положим верстку крестика, то нам их не придется искать в скриптах, а значит код станет чище и проще

2022-03-17 13:57 UTC, Philiuh commented on dev/res/js-dev/components/modal/renderModal.js
> +const renderModal = (cardData, error) => {
забыл убрать, соре))

2022-03-17 14:00 UTC, Philiuh commented on dev/res/js-dev/components/modal/renderModal.js
> +      <button class="close-button--modal"></button>
надо будет вообще над неймингом селекторов поработать мне и зарефакторить, чтобы было все как по учебнику

2022-03-17 21:24 UTC, Philiuh commented on dev/res/js-dev/components/fetch/renderCards.js
> +/* eslint-disable camelcase */
конкретно в данном случае придется много где вставлять правило отключения кэмелкейса в еслинте, + его не отключить в возврате строки 
![image](https://user-images.githubusercontent.com/37549039/158897462-08a97445-6b99-4082-8fdf-dff8af6e0dcb.png)

2022-03-17 21:39 UTC, Philiuh commented on dev/res/js-dev/components/modal/renderModal.js
> +          ? '<div class="reserved-img"><p class="reserved-announcement reserved-announcement--modal">В заповеднике</p></div>'
Не очень понял, что можно сделать псевдоэлементами?

2022-03-25 13:40 UTC, BogdanovBogdan commented on dev/res/js-dev/components/fetch/renderCards.js
> +/* eslint-disable camelcase */
Согласен

2022-03-25 13:43 UTC, BogdanovBogdan commented on dev/res/js-dev/components/modal/renderModal.js
> +// чтоб не выглядело ебано
.

2022-03-25 13:46 UTC, BogdanovBogdan commented on dev/res/js-dev/components/modal/renderModal.js
> +const renderModal = (cardData, error) => {
.

2022-03-25 13:47 UTC, BogdanovBogdan commented on dev/res/sass/components/modal/_modal.scss
> +  left: $modalWidth + 11px;
.

2022-03-25 15:27 UTC, BogdanovBogdan commented
async без await определились что не нужны

2022-03-25 15:29 UTC, BogdanovBogdan commented
добавить фигурные скобки для большей читабельности: https://github.com/Philiuh/tesk_task_ruport/blob/modal_card/dev/res/js-dev/components/modal/renderModal.js#L16

2022-03-25 15:46 UTC, BogdanovBogdan requested changes

2022-03-25 15:46 UTC, BogdanovBogdan commented on dev/res/js-dev/components/modal/renderModal.js
> +  modalCardContainer = document.querySelector('.modal__background');
если modalCardContainer то тогда и класс пускай будет говорить, что это контейнер модалки, а не бэкграунд)

2022-03-25 15:46 UTC, BogdanovBogdan commented on dev/res/js-dev/components/modal/renderModal.js
> +        <button class="card__button modal__button accept">Принять</button>
у тебя сейчас основные стили задаются для класса accept, предлагаю задать их для класса card__button, а реджект сделать как модификатор

2022-03-25 15:46 UTC, BogdanovBogdan commented on dev/res/sass/components/card/_card.scss
> +// можно ли во избежании !important определить бордер так,
можна!

2022-03-25 15:46 UTC, BogdanovBogdan commented on dev/res/sass/components/modal/_modal.scss
> +  cursor: auto;
Это для чего?

2022-03-25 15:46 UTC, BogdanovBogdan commented on dev/res/sass/components/modal/_modal.scss
> +$annoOffset: 30px;
что за игры тут

2022-03-28 09:16 UTC, Philiuh commented on dev/res/js-dev/components/modal/renderModal.js
> +      <h2 class="card__name modal__name">${name}</h2>
но в таком случае придется прописывать стили от модалки в файл стилей карточек для card_name и card_info, тем самым нарушая консистентность. стили от модалки, получаеца, будут и в card.scss, и в modal.scss

2022-03-29 10:39 UTC, BogdanovBogdan requested changes

2022-03-29 10:39 UTC, BogdanovBogdan commented on dev/res/js-dev/components/modal/renderModal.js
> +};
Проще будет задать листенер стразу на кнопку закрытия, чем на модалку и потом по таргету искать эту кнопку

2022-03-29 10:39 UTC, BogdanovBogdan commented on dev/res/js-dev/components/modal/renderModal.js
> +  subscribeModal();
тут можно сделать одну функцию `subscribe`, где у тебя будут храниться все листенеры

2022-03-29 10:39 UTC, BogdanovBogdan commented on dev/res/sass/components/card/_card.scss
> +      max-height: 146px;
тут у тебя высота равна высоте изображения, поэтому это значение можно вынести в переменную и юзать ее

2022-03-29 10:39 UTC, BogdanovBogdan commented on dev/res/sass/components/card/_card.scss
> +      position: absolute;
лишнее

2022-03-29 10:39 UTC, BogdanovBogdan commented on dev/res/sass/components/card/_card.scss
> +      padding-top: 16px;
это значение у тебя сейчас плюсуется к высоте, получается что высота псевдоэлемента выше самого изображения на 16px

2022-03-29 10:39 UTC, BogdanovBogdan commented on dev/res/sass/components/card/_card.scss
> +      border-radius: 6px 6px 0 0;
у тебя уже есть это свойство у самой карточки. Чтобы не дублировать для каждого ребенка карточки это сво-во, можно самой карточке сделать `overflow: hidden`

2022-03-29 10:39 UTC, BogdanovBogdan commented on dev/res/sass/components/card/_card.scss
> +  @include tx-font-size(14px, 9.8px);
вообще не так важно line-height (и остальные значения, типа width, height и т.п.) задавать с точностью до дробного числа при условии если:
- это не ломает верстку
- нет требования вестать pixel perfect

я вообще округляю число до кратного пяти, т.е. здесь можно сделать просто 10px
з.ы. к свойству font-size это не относится, его нужно указывать точно, до целого числа, без дробных

2022-03-29 10:39 UTC, BogdanovBogdan commented on dev/res/sass/components/card/_card.scss
> +    @extend .card__button;
а для чего тут экстенд `.card__button`?

2022-04-03 23:55 UTC, Philiuh commented on dev/res/js-dev/components/modal/renderModal.js
> +      <h2 class="card__name modal__name">${name}</h2>
все еще не понимаю суть коммента, о чем речь

2022-04-04 00:31 UTC, Philiuh commented on dev/res/sass/components/card/_card.scss
> +    @extend .card__button;
мы же здесь создаем отдельный класс с модификатором card__button--reject, поэтому нужно здесь экстендить стили основного класса card__button. можно, конечно, без экстенда прописывать кнопке реджекта классы card__button card__button--reject, но зачем, если можно сделать проще

2022-04-04 10:15 UTC, BogdanovBogdan requested changes

2022-04-04 11:09 UTC, Philiuh commented on dev/res/sass/components/card/_card.scss
> +    @extend .card__button;
Аргумент засчитан, исправлю))

2022-04-05 08:12 UTC, BogdanovBogdan requested changes

2022-04-05 08:12 UTC, BogdanovBogdan commented on dev/res/js-dev/components/modal/renderModal.js
> +      <h2 class="card__name modal__name">${name}</h2>
имею ввиду наслодоваться при помощи экстенда, т.е. добавить экстенд модалки в .card_name и указать для него нужный размер шрифта...
Если описывать стили словами, то звучать будет так: если компонент .card__name находится в .modal__container, то нужно увеличить размер шрифта до 32px, например.

2022-04-06 13:15 UTC, BogdanovBogdan requested changes

2022-04-06 13:21 UTC, Philiuh commented on dev/res/sass/components/modal/_modal.scss
> +// сильнее, чем extend от класса modal__inner?
Собственно встал вопрос, как приоритезировать класс, если нельзя прокинуть !important

2022-04-06 16:17 UTC, BogdanovBogdan commented on dev/res/sass/components/modal/_modal.scss
> +// сильнее, чем extend от класса modal__inner?
неа, он не может быть сильнее, т.к. у него значение специфичность равна значению 1 (второй скрин), а у экстенда   с классом - 2

игнорится потому что специфичность у класса `.modal__inner .card__info` больше чем у `.modal__text`
![image](https://user-images.githubusercontent.com/49097483/162019694-3d5b990f-1626-45db-86e6-035e3d85ebae.png)

Вот тут изображено, у каких из этих классов какая специфичность:
![image](https://user-images.githubusercontent.com/49097483/162020204-7900c4b0-745d-4709-88f7-13350dde8b0e.png)

2022-04-06 16:17 UTC, BogdanovBogdan commented on dev/res/sass/components/modal/_modal.scss
> +// сильнее, чем extend от класса modal__inner?
Какие решения видишь?)

2022-04-07 07:23 UTC, BogdanovBogdan requested changes

2022-04-07 08:12 UTC, BogdanovBogdan requested changes

2022-04-07 08:12 UTC, BogdanovBogdan commented on dev/res/sass/components/modal/_modal.scss
> +.modal {
А этот класс где-то используется?

2022-04-07 08:12 UTC, BogdanovBogdan commented on dev/res/sass/components/modal/_modal.scss
> +.reserved--modal {
А этот класс где-то используется?

2022-04-07 08:23 UTC, Philiuh commented on dev/res/js-dev/components/fetch/renderCards.js
> +    class="${in_reserve ? 'card card--reserved' : 'card'}" >
да, исправил и пока не вылил. хотел вылить с фиксом стилей для модалки

2022-04-07 08:57 UTC, Philiuh commented on dev/res/sass/components/modal/_modal.scss
> +.reserved--modal {
renderModal.js 
![image](https://user-images.githubusercontent.com/37549039/162161625-dcea1fb6-2039-4c93-ba18-520c7f6581bb.png)

2022-04-11 14:28 UTC, BogdanovBogdan requested changes

2022-04-11 14:28 UTC, BogdanovBogdan commented on dev/res/sass/components/modal/_modal.scss
> +  object-fit: cover;
это свойство уже есть у класса .card__img

2022-04-11 14:28 UTC, BogdanovBogdan commented on dev/res/js-dev/components/modal/renderModal.js
> +      <p class="card__info modal__text">${text}</p>
тут напрашивается другое название класса, т.к. компонент по макету меньше, чем тот же текст с классами card_info, плюсом решения реализации с другим классом будет еще отсутствие ебатни с приоритизацией классов

2022-04-11 14:41 UTC, BogdanovBogdan requested changes

2022-04-11 14:41 UTC, BogdanovBogdan commented on dev/res/sass/components/modal/_modal.scss
> +  &::before {
можно избавиться от этого класса добавив этот псевдоэлемент в класс card--reserved при условии, что он является дочерним компонентом modal__container

2022-04-11 14:41 UTC, BogdanovBogdan commented on dev/res/sass/components/modal/_modal.scss
> +}
Решили вместе, что можно избежать задания стилей таким способом, если создать новый класс для modal__text, например card__description

2022-04-14 08:10 UTC, BogdanovBogdan commented on dev/res/js-dev/components/modal/renderModal.js
> +      <div class="card__button-list modal__button-list">
у тебя из стилей от `card__button-list` по сути, ничего не осталось, все перебилось `modal__button-list`... думаю можно избавиться от класса `card__button-list`
![image](https://user-images.githubusercontent.com/49097483/163342496-0a141419-5938-450f-9530-256fa7760c7c.png)

2022-04-14 08:22 UTC, BogdanovBogdan approved these changes

2022-04-14 09:40 UTC, merged